### ISSUE TITLE
Cleanup recipe.yml

### ISSUE THREAD

**Issue by mecattaf** [mecattaf/zen#15]
Too many packages listed in rpm-ostree , it would be preferable to group them following:
```
modules:
  - type: rpm-ostree
    # rest of the module config...
  - from-file: common-packages.yml
  ```
  
  instructions: https://blue-build.org/reference/recipe/
